"""Add new profile fields for LinkedIn-like profile

Revision ID: 06c2ffed97ed
Revises: 
Create Date: 2025-10-12 11:20:53.651876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c2ffed97ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cover_photo_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('projects', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('professional_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('professional_summary')
        batch_op.drop_column('projects')
        batch_op.drop_column('certifications')
        batch_op.drop_column('languages')
        batch_op.drop_column('cover_photo_url')
        batch_op.drop_column('website_url')

    # ### end Alembic commands ###
