"""remove batch_number and is_member fields

Revision ID: 3af291a98314
Revises: 34495fcc32bf
Create Date: 2026-03-08 23:17:19.860878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af291a98314'
down_revision = '34495fcc32bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_member')
        batch_op.drop_column('batch_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_number', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_member', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
