"""Add extended profile fields

Revision ID: 5a06f28dd94a
Revises: a1267a0c7c4e
Create Date: 2026-02-20 04:11:56.936970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a06f28dd94a'
down_revision = 'a1267a0c7c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headline', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cover_photo_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('projects', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('publications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('professional_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('experience')
        batch_op.drop_column('education')
        batch_op.drop_column('professional_summary')
        batch_op.drop_column('publications')
        batch_op.drop_column('projects')
        batch_op.drop_column('certifications')
        batch_op.drop_column('languages')
        batch_op.drop_column('website_url')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('cover_photo_url')
        batch_op.drop_column('location')
        batch_op.drop_column('headline')

    # ### end Alembic commands ###
