"""Add read_at field to Message model

Revision ID: 5d99a54cbca5
Revises: f333112f4e24
Create Date: 2025-10-31 08:28:47.476080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d99a54cbca5'
down_revision = 'f333112f4e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('read_at')

    # ### end Alembic commands ###
