"""add university model

Revision ID: 820e3367e38f
Revises: 1e9c5ee43bb1
Create Date: 2026-03-08 22:48:44.796403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820e3367e38f'
down_revision = '1e9c5ee43bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_departments_university_id', 'universities', ['university_id'], ['id'])

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_profiles_university_id', 'universities', ['university_id'], ['id'])

    # Seed Sudanese pharmacy universities
    universities = [
        {'name': 'University of Khartoum', 'abbreviation': 'UoK', 'location': 'Khartoum'},
        {'name': 'Sudan University of Science and Technology', 'abbreviation': 'SUST', 'location': 'Khartoum'},
        {'name': 'University of Gezira', 'abbreviation': 'UoG', 'location': 'Madani'},
        {'name': 'Neelain University', 'abbreviation': 'NU', 'location': 'Khartoum'},
        {'name': 'International University of Africa', 'abbreviation': 'IUA', 'location': 'Khartoum'},
        {'name': 'Al Zaiem Al Azhari University', 'abbreviation': 'AZU', 'location': 'Khartoum'},
        {'name': 'National University-Sudan', 'abbreviation': 'NU-Sudan', 'location': 'Khartoum'},
        {'name': 'Omdurman Islamic University', 'abbreviation': 'OIU', 'location': 'Omdurman'},
        {'name': 'University of Medical Sciences and Technology', 'abbreviation': 'UMST', 'location': 'Khartoum'},
        {'name': 'National Ribat University', 'abbreviation': 'NRU', 'location': 'Khartoum'},
        {'name': 'Karary University', 'abbreviation': 'KU', 'location': 'Khartoum'},
        {'name': 'Ahfad University for Women', 'abbreviation': 'AUW', 'location': 'Omdurman'},
        {'name': 'University of Shendi', 'abbreviation': 'UoS', 'location': 'Shendi'},
        {'name': 'Merowe University of Technology', 'abbreviation': 'MUT', 'location': 'Merowe'},
        {'name': 'Elsheikh Abdallah Elbadri University', 'abbreviation': 'EABU', 'location': 'Madani'},
        {'name': 'University of Kassala', 'abbreviation': 'UoKsl', 'location': 'Kassala'},
        {'name': 'University of Gadarif', 'abbreviation': 'UoGd', 'location': 'Gadarif'},
        {'name': 'Red Sea University', 'abbreviation': 'RSU', 'location': 'Port Sudan'},
        {'name': 'University of Kordofan', 'abbreviation': 'UoKo', 'location': 'El-Obeid'},
        {'name': 'University of Nyala', 'abbreviation': 'UoN', 'location': 'Nyala'},
        {'name': 'University of Bahri', 'abbreviation': 'UoB', 'location': 'Khartoum'},
        {'name': 'The Future University', 'abbreviation': 'TFU', 'location': 'Khartoum'},
        {'name': 'Nile Valley University', 'abbreviation': 'NVU', 'location': 'Atbara'},
        {'name': 'Omdurman Ahlia University', 'abbreviation': 'OAU', 'location': 'Omdurman'},
        {'name': 'University of Bakhtalruda', 'abbreviation': 'UoBR', 'location': 'Ad-Damazin'},
    ]

    from datetime import datetime
    for uni in universities:
        op.execute(
            sa.text(f"INSERT INTO universities (name, abbreviation, location, is_active, created_at) "
                    f"VALUES ('{uni['name']}', '{uni['abbreviation']}', '{uni['location']}', 1, '{datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')}')")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profiles_university_id', type_='foreignkey')
        batch_op.drop_column('university_id')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_departments_university_id', type_='foreignkey')
        batch_op.drop_column('university_id')

    op.drop_table('universities')
    # ### end Alembic commands ###
