"""Add index to user_skills on skill_id

Revision ID: 8ef4667aed09
Revises: a5e312567a39
Create Date: 2026-02-21 02:55:07.928020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef4667aed09'
down_revision = 'a5e312567a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_skills_skill_id'), ['skill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_skills_skill_id'))

    # ### end Alembic commands ###
