"""Remove github_url field from User model

Revision ID: 8f1f79bc8223
Revises: da586f3cc742
Create Date: 2025-10-30 17:16:33.010499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1f79bc8223'
down_revision = 'da586f3cc742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('github_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_url', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
