"""Drop old monolithic columns from User

Revision ID: 9fe7276b4580
Revises: 5a06f28dd94a
Create Date: 2026-02-20 04:15:38.313709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe7276b4580'
down_revision = '5a06f28dd94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('professional_summary')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('education')
        batch_op.drop_column('name')
        batch_op.drop_column('profile_picture_url')
        batch_op.drop_column('projects')
        batch_op.drop_column('headline')
        batch_op.drop_column('certifications')
        batch_op.drop_column('languages')
        batch_op.drop_column('experience')
        batch_op.drop_column('publications')
        batch_op.drop_column('cover_photo_url')
        batch_op.drop_column('website_url')
        batch_op.drop_column('skills')
        batch_op.drop_column('about')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('about', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cover_photo_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('publications', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('experience', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('languages', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('headline', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('projects', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_picture_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('education', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('professional_summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
