"""add mentorship fields

Revision ID: a1bdfc5b0d2c
Revises: 37c16ac0cd93
Create Date: 2026-04-01 13:08:15.171324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bdfc5b0d2c'
down_revision = '37c16ac0cd93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentorship_program', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('mentorship_duration', sa.String(length=100), nullable=True))

    with op.batch_alter_table('researcher_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentorship_program', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('mentorship_duration', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('researcher_profiles', schema=None) as batch_op:
        batch_op.drop_column('mentorship_duration')
        batch_op.drop_column('mentorship_program')

    with op.batch_alter_table('alumni_profiles', schema=None) as batch_op:
        batch_op.drop_column('mentorship_duration')
        batch_op.drop_column('mentorship_program')

    # ### end Alembic commands ###
