"""Remove cover_photo_url from profiles

Revision ID: a5e312567a39
Revises: 232e10052396
Create Date: 2026-02-20 15:42:52.721085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e312567a39'
down_revision = '232e10052396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('cover_photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_photo_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
