"""Add core schema and profiles

Revision ID: c5e38d286463
Revises: add_google_id_to_user
Create Date: 2026-02-20 03:59:09.622041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e38d286463'
down_revision = 'add_google_id_to_user'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('faculty_name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alumni_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('open_to_mentor', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('researcher_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('academic_rank', sa.String(length=150), nullable=True),
    sa.Column('lab_name', sa.String(length=150), nullable=True),
    sa.Column('office_location', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('student_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('academic_level', sa.String(length=100), nullable=True),
    sa.Column('gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('cv_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_skills',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'skill_id')
    )
    
    # Explicitly create enum type for postgres
    userrole = sa.Enum('STUDENT', 'ALUMNI', 'RESEARCHER', 'ADMIN', name='userrole')
    userrole.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', userrole, nullable=False, server_default='STUDENT'))
        batch_op.drop_index(batch_op.f('ix_user_google_id'))
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_user_google_id'), ['google_id'], unique=True)
        batch_op.drop_column('role')

    op.drop_table('user_skills')
    op.drop_table('student_profiles')
    op.drop_table('researcher_profiles')
    op.drop_table('profiles')
    op.drop_table('alumni_profiles')
    op.drop_table('skills')
    op.drop_table('departments')
    
    # Drop explicitly created enum type
    userrole = sa.Enum('STUDENT', 'ALUMNI', 'RESEARCHER', 'ADMIN', name='userrole')
    userrole.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
