"""Remove profile_picture_url field from User model

Revision ID: da586f3cc742
Revises: db23483ecda3
Create Date: 2025-10-14 07:31:01.539043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da586f3cc742'
down_revision = 'db23483ecda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
