"""add researcher mentor opt-in and job applications

Revision ID: eb8617734a0a
Revises: 9fe7276b4580
Create Date: 2026-02-20 15:03:03.754326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8617734a0a'
down_revision = '9fe7276b4580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('researcher_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_to_mentor', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('researcher_profiles', schema=None) as batch_op:
        batch_op.drop_column('open_to_mentor')

    # ### end Alembic commands ###
